<script>
jQuery('#tree').fancytree(
{
	extensions: ["dnd", "edit"],
	dnd:
	{
		autoExpandMS: 400,
		focusOnClick: false,
		preventVoidMoves: true,
		preventRecursiveMoves: true,
		dragStart: function(node, data)
		{
			return true;
		},
		dragEnter: function(node, data)
		{
			return true;
		},
		dragDrop: function(node, data)
		{
			var loaderArea = $$('#html-body .wrapper')[0];
			Position.clone($(loaderArea), $('loading-mask'), {offsetLeft:-2});
			toggleSelectsUnderBlock($('loading-mask'), false);
			jQuery('#loading-mask').show();

			jQuery.post("<?php echo Mage::getUrl('adminhtml/cmsTree/saveTree') ?>",
			{
				form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
				store_id: <?php echo $this->getCurrentStoreID() ?>,
				node_id: data.otherNode.data.id,
				target_node_id: data.node.data.id,
				hit_mode: data.hitMode
			})
			.always(function(data)
			{
				if (!data.result)
				{
					alert("<?php echo $this->__('CmsTree: An error occurred while saving') ?>");
				}

				jQuery('#loading-mask').hide();
			});

			data.otherNode.moveTo(node, data.hitMode);
		}
	},
	activate: function(event, data)
	{
		var node = data.node;

		if (node.data.href)
		{
			window.open(node.data.href, node.data.target);
		}
	},
	init: function(event, data)
	{
		jQuery('#tree').css('display', 'block');
	}
});
</script>
