<div class="content-header">
	<h3 class="icon-head head-categories"><?php echo $this->__('Manage Pages') ?></h3>
</div>

<p class="switcher">
	<label for="store_switcher"><?php echo $this->__('Choose Store View:') ?></label>
	<select name="store_switcher" id="store_switcher" class="left-col-block" onchange="location = this.value;">
	
		<?php foreach (Mage::helper('marcelgeidel_cmstree')->getStores() as $store): ?>
		<option value="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/cms_page/index', array('store_id' => $store->getId())); ?>" <?php echo $store->getId() == $this->getCurrentStoreID() ? 'selected' : '' ?> class="even"><?php echo $store->getName(); ?></option>
		<?php endforeach; ?>
		
	</select>
	<a href="http://www.magentocommerce.com/knowledge-base/entry/understanding-store-scopes" onclick="this.target='_blank'" title="<?php echo $this->__('What is this?') ?>" class="link-store-scope"><?php echo $this->__('What is this?') ?></a>
</p>

<div class="button-wrapper">
	<button title="<?php echo $this->__('Add New Page') ?>" type="button" class="scalable add" onclick="setLocation('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/cms_page/new', array('store_id' => $this->getCurrentStoreID())); ?>')">
		<span><span><span><?php echo $this->__('Add New Page') ?></span></span></span>
	</button>
</div>

<div id="tree" style="display: none;">
	<?php echo $this->getTreeHtml() ?>
</div>

<?php echo $this->getChildHtml('script') ?>
